---
- hosts: all
  gather_facts: yes
  become: false
  tasks:
  - name: Dağıtım
    debug: msg="{{ ansible_distribution }}"
  - name: Dağıtım versiyonu
    debug: msg="{{ ansible_distribution_version}}"
#  - name: Distribution major version
#    debug: msg="{{ ansible_distribution_major_version }}"
